### ISSUE TITLE
Android version. Проблема аварийное завершение программы при отсутствии подключения к Интернету. 

### ISSUE THREAD

**Issue by IlyaKryukov** [dkblock/YarTransport#10]
Порядок действий:
1) Отключаем передачу данных на мобильном устройстве
2) Запускаем приложение 
3) Выбираем любой маршрут
4) Нажимаем кнопку "найти транспорт"
Существующее поведение: выводится ошибка и приложение закрывается.
Ожидаемое поведение: появление уведомления об отсутствия подключения к Интернету
![image](https://user-images.githubusercontent.com/45962769/50300623-0bbc3500-0496-11e9-86ee-fbf6d3e5ffa6.png)

**Comment by FoxHanter** [comment]
fixed
