### ISSUE TITLE
Android version. Проблема аварийного завершения программы при "пустом запросе"

### ISSUE THREAD

**Issue by IlyaKryukov** [dkblock/YarTransport#11]
Порядок действий:
1) Запускаем приложение
2) Нажимаем кнопку "найти транспорт"
Существующие поведение: выводится ошибка и приложение закрывается.
Ожидаемое поведение: появление уведомления об отсутствии маршрута.
![image](https://user-images.githubusercontent.com/45962769/50300977-15926800-0497-11e9-8086-5a6f3889f10d.png)

**Comment by FoxHanter** [comment]
fixed
