### ISSUE TITLE
Android version. Не находит остановку по названию в нижнем регистре.

### ISSUE THREAD

**Issue by LazyBall** [dkblock/YarTransport#13]
Порядок действий:
1. Запускаем приложение.
2. Нажимаем на поле "Откуда".
3. Нажимаем на значок поиска в появившемся списке.
4. Вводим "октябрьская площадь".
Существующее поведение: отображается "Not found!".
Ожидаемое поведение: отображается вариант "Октябрьская площадь".
![image](https://user-images.githubusercontent.com/46029218/50303836-5b532e80-049f-11e9-9c79-d3959498d942.png)

**Comment by FoxHanter** [comment]
Fixed
