### ISSUE TITLE
Android version. Не отображается результат поиска.

### ISSUE THREAD

**Issue by LazyBall** [dkblock/YarTransport#14]
Порядок действий:
1. Запускаем приложение.
2. Нажимаем на поле "Откуда".
3. Выбираем в появившемся списке остановку "ЯШЗ".
4. Нажимаем "ОК".
5. Нажимаем на поле "Куда".
6. Выбираем в появившемся списке остановку "Улица Победы".
7. Нажимаем "ОК"
8. Нажимаем "Найти транспорт".
5. Существующее поведение: на короткий промежуток времени отображается строка "Подождите, идет загрузка", потом она исчезает и ничего не появляется.
Ожидаемое поведение: отображается строка "Подождите, идет загрузка", после чего либо отображаются найденные транспортные средства, идущие по данному маршруту, либо сообщение о том, что таких транспортных средств нет.
![image](https://user-images.githubusercontent.com/46029218/50305239-42e51300-04a3-11e9-8c5e-66b94ca05f28.png)

**Comment by FoxHanter** [comment]
fixed
