### ISSUE TITLE
Некорректное поведение "Избранного"

### ISSUE THREAD

**Issue by IlyaKryukov** [dkblock/YarTransport#4]
1. Добавляем в "Избранное" 2 маршрута с одинаковым названием.
2. Удаляем один из них.
3. Попытка открыть/удалить оставшiеся маршруты приводит к аварийному завершению.

Ожидаемое поведение: удалится один из маршрутов, а остальные будут корректно открываться/удалятЬся.

**Comment by dkblock** [comment]
Понятно спасибо

**Comment by dkblock** [comment]
fixed.
