### ISSUE TITLE
Долгое ожидание подключения

### ISSUE THREAD

**Issue by IlyaKryukov** [dkblock/YarTransport#5]
При поиске маршрута "12-микрорайон - площадь Карла Маркса" в title окна появляется надпись (Not Responding). В одном из тестов при поиске данного маршрута программа аварийно завершила работу.

Ожидаемое поведение: обработка долгого соединения и вывод ошибки "Долгое соединение!"

**Comment by dkblock** [comment]
Понятно спасибо

**Comment by dkblock** [comment]
fixed.
