### ISSUE TITLE
Desktop version. Аварийное завершение работы программы при отсутствии подключения к Интернету.

### ISSUE THREAD

**Issue by LazyBall** [dkblock/YarTransport#6]
Порядок действий:
1. Отключаем доступ компьютера в сеть Интернет.
2. Запускаем программу.
3. В поле пункта отправления "А" вводим "Московский вокзал".
4. В поле пункта прибытия "В" вводим "Октябрьская площадь".
5. Нажимаем на кнопку "Поиск".
Существующее поведение: происходит закрытие программы.
Ожидаемое поведение: появление окна с уведомлением об отсутствии подключения к Интернету.
![image](https://user-images.githubusercontent.com/46029218/50296278-381e8400-048b-11e9-9f70-15a6c8894496.png)

**Comment by dkblock** [comment]
fixed.
