### ISSUE TITLE
Desktop version. Программа не реагирует на нажатие на кнопку поиска.

### ISSUE THREAD

**Issue by LazyBall** [dkblock/YarTransport#7]
Порядок действий:
1. Запускаем программу. 
2. В поле пункта отправления "А" вводим любое значение, не совпадающее со значениями из списка подсказок. 
3. В поле пункта прибытия "В" вводим любое значение. 
4. Нажимаем на кнопку поиска. 
Существующее поведение: программа не реагирует на нажатие. 
Ожидаемое поведение: вывод окна с сообщением "Не существует транспорта, следующего по заданному маршруту".
![image](https://user-images.githubusercontent.com/46029218/50296415-8469c400-048b-11e9-9422-acfa4aec2ba1.png)

**Comment by dkblock** [comment]
fixed.
