### ISSUE TITLE
Desktop version. Логическая ошибка в тексте всплывающего окна.

### ISSUE THREAD

**Issue by LazyBall** [dkblock/YarTransport#8]
Порядок действий:
1. Запускаем программу.
2. В поле пункта отправления "А" вводим "Московский вокзал".
3. В поле пункта прибытия "В" вводим "Октябрьская площадь".
4. В колонке "Транспорт" убираем галочки у полей "Автобус", "Троллейбус", "Трамвай", "Маршрутка".
5. Нажимаем на кнопку "Поиск".
Существующее поведение: появляется окно с текстом "В данный момент на линии нет транспорта, следующего по заданному маршруту".
Ожидаемое поведение: появляется окно, в котором пользователю будет дана подсказка о том, что следует проверить параметры поиска.
![image](https://user-images.githubusercontent.com/46029218/50296546-c6930580-048b-11e9-969e-3eb3cb838059.png)

**Comment by dkblock** [comment]
fixed.
