### ISSUE TITLE
Android version. Проблема отображения избранных маршрутов.

### ISSUE THREAD

**Issue by LazyBall** [dkblock/YarTransport#9]
Порядок действий:
1. Запускаем приложение.
2. В поле "Откуда" выбираем "Московский вокзал".
3. В поле "Куда" выбираем Богоявленская площадь".
4. Нажимаем на звездочку, сохраняя маршрут в избранное.
5. Переходим в избранное.
Существующее поведение: отображается строка "SearchWaySystem.FavoriteRoutesNode"
Ожидаемое поведение: отображен маршрут, который мы отметили как избранный.
![image](https://user-images.githubusercontent.com/46029218/50297806-b597c380-048e-11e9-92e9-0d25bfae78bb.png)
![image](https://user-images.githubusercontent.com/46029218/50297823-bdeffe80-048e-11e9-8b08-ec0e2a0a0487.png)

**Comment by FoxHanter** [comment]
fixed
